version: '3'
services:
    app:
        build: .
        command: npm run start
        ports:
            - 3333:3333
        volumes:
            - .:/src/
            - nodemodules:/src/node_modules

volumes:
    nodemodules: {}
